### ISSUE TITLE
Content not visible

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/kraken-good-accessibility#1]
<img width="525" alt="Screenshot 2020-09-27 at 4 08 48 AM" src="https://user-images.githubusercontent.com/55109487/94359876-9c667280-0077-11eb-94cb-25f6dfd9b461.png">

1) Markbot errors
2) The property "color: #fff;" does not apply on H1
3) Can't make the nav bar visible in header nor footer
4) How to get the desired hamburger icon

@mackenzierose

**Comment by VanshitaGandhi** [comment]
@MacKenzieRose

Hi, just an update on this assignment :—
<img width="524" alt="Screenshot 2020-09-28 at 3 12 02 PM" src="https://user-images.githubusercontent.com/55109487/94475379-fad94100-019c-11eb-9db2-0018a350b297.png">

1) The background-color issue
2) Matching the visual difference

The code is pushed.

**Comment by MacKenzieRose** [comment]
Hey!

So for your contrast issue, when you disable your images in the browser, you need to be able to still read the text. If you add in a background colour for your header in your CSS (I put it around line 33), it should pass, assuming there is a high enough contrast with the text.

For the visual differences, one thing that may help is adding padding around your body text, so it doesn't extend all of the way to the edge of the browser window. Your footer also looks like it's the farthest from matching in terms of individual elements, so double check your CSS there.

Let me know how that goes, and re-tag me if you need more help 🙂

**Comment by VanshitaGandhi** [comment]
1) So even after applying the background-colour, I still get the same error
2) I'm unable to change the font-colour and font-style for my H1
3) The footer screenshots aren't visible so I can't visually match it.
4) Adding padding to the body increases the visual difference.

@MacKenzieRose

**Comment by MacKenzieRose** [comment]
In your CSS, there is more than one place that you can target your header styling; make sure you're applying it in the right place (or both, if you're not sure). Make sure the background colour you use is `#1e7c74` for those sections.

For your H1, because whatever loads last in your CSS file is what the browser displays, the CSS code you have at ~line 127 (the `article div:first-child::first-line` ) is what's styling your H1. 

For your footer styling, it looks like you're right: Markbot isn't looking that far down the page, so don't stress about it! For your visual styling, your `div` is introducing some extra padding (and therefore spacing between paragraphs), so adjusting that may help. Fix the other stuff first, and re-tag me if you need more help here 😄

**Comment by VanshitaGandhi** [comment]
Hey, I fixed it! Thank you so much for the help! @MacKenzieRose
